export const mockVendors = [
  {
    id: 'vendor_001',
    vendorCode: 'VEN001',
    vendorName: 'Booking.com',
    vendorType: 'OTA',
    isActive: true,
    businessModel: 'COMMISSION',
    integrationSettings: {
      apiEndpoint: 'https://api.booking.com',
      apiKey: 'encrypted_key_001',
      ftpDetails: null,
      emailSettings: {
        incomingEmail: 'invoices@booking.com',
        supportEmail: 'support@booking.com',
      },
    },
    invoiceSettings: {
      defaultCurrency: 'USD',
      invoicePrefix: 'BKG',
      dueDays: 30,
      paymentTerms: 'Net 30',
      taxRate: 10,
    },
    extractionSettings: {
      templateId: 'template_booking',
      dateFormat: 'MM/DD/YYYY',
      numberFormat: 'en-US',
      customFields: [],
    },
    reconciliationSettings: {
      autoReconcile: true,
      matchingThreshold: 95,
      defaultRules: ['rule_001', 'rule_002'],
      bookingSourceField: 'reservation_number',
      amountTolerancePercentage: 1,
    },
    contacts: [
      {
        name: 'John Doe',
        email: 'john@booking.com',
        phone: '+1234567890',
        role: 'Finance Manager',
        isPrimary: true,
      },
    ],
    createdAt: '2024-01-15T10:00:00Z',
    updatedAt: '2024-01-20T15:30:00Z',
  },
  {
    id: 'vendor_002',
    vendorCode: 'VEN002',
    vendorName: 'Expedia',
    vendorType: 'OTA',
    isActive: true,
    businessModel: 'NET_RATE',
    integrationSettings: {
      apiEndpoint: 'https://api.expedia.com',
      apiKey: 'encrypted_key_002',
      ftpDetails: {
        host: 'ftp.expedia.com',
        port: 21,
        username: 'invoice_user',
        directory: '/invoices',
      },
      emailSettings: {
        incomingEmail: 'invoices@expedia.com',
        supportEmail: 'support@expedia.com',
      },
    },
    invoiceSettings: {
      defaultCurrency: 'USD',
      invoicePrefix: 'EXP',
      dueDays: 45,
      paymentTerms: 'Net 45',
      taxRate: 8,
    },
    extractionSettings: {
      templateId: 'template_expedia',
      dateFormat: 'DD/MM/YYYY',
      numberFormat: 'en-US',
      customFields: [],
    },
    reconciliationSettings: {
      autoReconcile: false,
      matchingThreshold: 90,
      defaultRules: ['rule_003', 'rule_004'],
      bookingSourceField: 'booking_id',
      amountTolerancePercentage: 2,
    },
    contacts: [
      {
        name: 'Jane Smith',
        email: 'jane@expedia.com',
        phone: '+1987654321',
        role: 'Account Manager',
        isPrimary: true,
      },
    ],
    createdAt: '2024-01-10T08:00:00Z',
    updatedAt: '2024-01-18T12:00:00Z',
  },
  {
    id: 'vendor_003',
    vendorCode: 'VEN003',
    vendorName: 'Hotels.com',
    vendorType: 'OTA',
    isActive: true,
    businessModel: 'COMMISSION',
    integrationSettings: {
      apiEndpoint: 'https://api.hotels.com',
      apiKey: 'encrypted_key_003',
      ftpDetails: null,
      emailSettings: {
        incomingEmail: 'billing@hotels.com',
        supportEmail: 'partner-support@hotels.com',
      },
    },
    invoiceSettings: {
      defaultCurrency: 'USD',
      invoicePrefix: 'HTC',
      dueDays: 30,
      paymentTerms: 'Net 30',
      taxRate: 9.5,
    },
    extractionSettings: {
      templateId: 'template_hotels',
      dateFormat: 'YYYY-MM-DD',
      numberFormat: 'en-US',
      customFields: ['commission_rate', 'partner_code'],
    },
    reconciliationSettings: {
      autoReconcile: true,
      matchingThreshold: 92,
      defaultRules: ['rule_001', 'rule_005'],
      bookingSourceField: 'confirmation_number',
      amountTolerancePercentage: 1.5,
    },
    contacts: [
      {
        name: 'Sarah Johnson',
        email: 'sarah.j@hotels.com',
        phone: '+1555123456',
        role: 'Partner Relations',
        isPrimary: true,
      },
      {
        name: 'Mike Chen',
        email: 'mike.c@hotels.com',
        phone: '+1555123457',
        role: 'Technical Support',
        isPrimary: false,
      },
    ],
    createdAt: '2024-01-05T09:00:00Z',
    updatedAt: '2024-01-25T14:20:00Z',
  },
  {
    id: 'vendor_004',
    vendorCode: 'VEN004',
    vendorName: 'Agoda',
    vendorType: 'OTA',
    isActive: true,
    businessModel: 'COMMISSION',
    integrationSettings: {
      apiEndpoint: 'https://api.agoda.com/v2',
      apiKey: 'encrypted_key_004',
      ftpDetails: {
        host: 'sftp.agoda.com',
        port: 22,
        username: 'partner_invoice',
        directory: '/invoices/incoming',
      },
      emailSettings: {
        incomingEmail: 'statements@agoda.com',
        supportEmail: 'partnersupport@agoda.com',
      },
    },
    invoiceSettings: {
      defaultCurrency: 'EUR',
      invoicePrefix: 'AGD',
      dueDays: 60,
      paymentTerms: 'Net 60',
      taxRate: 12,
    },
    extractionSettings: {
      templateId: 'template_agoda',
      dateFormat: 'DD-MM-YYYY',
      numberFormat: 'de-DE',
      customFields: ['property_id', 'commission_type'],
    },
    reconciliationSettings: {
      autoReconcile: true,
      matchingThreshold: 93,
      defaultRules: ['rule_001', 'rule_006', 'rule_007'],
      bookingSourceField: 'agoda_booking_id',
      amountTolerancePercentage: 0.5,
    },
    contacts: [
      {
        name: 'Lisa Wong',
        email: 'lisa.wong@agoda.com',
        phone: '+6591234567',
        role: 'Regional Manager',
        isPrimary: true,
      },
    ],
    createdAt: '2023-12-20T08:00:00Z',
    updatedAt: '2024-01-22T16:45:00Z',
  },
  {
    id: 'vendor_005',
    vendorCode: 'VEN005',
    vendorName: 'TripAdvisor',
    vendorType: 'OTA',
    isActive: false,
    businessModel: 'REFERRAL',
    integrationSettings: {
      apiEndpoint: 'https://api.tripadvisor.com',
      apiKey: 'encrypted_key_005',
      ftpDetails: null,
      emailSettings: {
        incomingEmail: 'invoices@tripadvisor.com',
        supportEmail: 'help@tripadvisor.com',
      },
    },
    invoiceSettings: {
      defaultCurrency: 'USD',
      invoicePrefix: 'TRP',
      dueDays: 30,
      paymentTerms: 'Net 30',
      taxRate: 8.5,
    },
    extractionSettings: {
      templateId: 'template_tripadvisor',
      dateFormat: 'MM/DD/YYYY',
      numberFormat: 'en-US',
      customFields: [],
    },
    reconciliationSettings: {
      autoReconcile: false,
      matchingThreshold: 88,
      defaultRules: ['rule_008'],
      bookingSourceField: 'ta_reference',
      amountTolerancePercentage: 3,
    },
    contacts: [
      {
        name: 'David Brown',
        email: 'david.b@tripadvisor.com',
        phone: '+1617123456',
        role: 'Account Executive',
        isPrimary: true,
      },
    ],
    createdAt: '2023-11-15T10:00:00Z',
    updatedAt: '2024-01-10T11:30:00Z',
  },
];

export const mockExtractions = [
  {
    id: 'ext_001',
    invoiceId: 'inv_001',
    vendorId: 'vendor_001',
    vendorName: 'Booking.com',
    invoiceNumber: 'BKG-2024-001',
    invoiceDate: '2024-01-15T00:00:00Z',
    dueDate: '2024-02-14T00:00:00Z',
    totalAmount: 5000.0,
    currency: 'USD',
    extractedData: {
      headerInfo: {
        invoiceNumber: 'BKG-2024-001',
        vendorAddress: '123 Booking Street, Amsterdam',
        customerName: 'Your Hotel Chain',
      },
      lineItems: [
        {
          lineNumber: 1,
          description: 'Hotel Booking - Hilton NYC',
          quantity: 2,
          unitPrice: 250.0,
          amount: 500.0,
          bookingReference: 'BK123456',
          checkInDate: '2024-01-20T00:00:00Z',
          checkOutDate: '2024-01-22T00:00:00Z',
          guestName: 'John Smith',
          propertyName: 'Hilton New York',
          roomType: 'Deluxe Double',
        },
        {
          lineNumber: 2,
          description: 'Hotel Booking - Marriott LA',
          quantity: 3,
          unitPrice: 300.0,
          amount: 900.0,
          bookingReference: 'BK123457',
          checkInDate: '2024-01-25T00:00:00Z',
          checkOutDate: '2024-01-28T00:00:00Z',
          guestName: 'Jane Doe',
          propertyName: 'Marriott Los Angeles',
          roomType: 'Executive Suite',
        },
      ],
      summary: {
        subtotal: 4500.0,
        tax: 450.0,
        fees: 50.0,
        total: 5000.0,
      },
    },
    extractionMethod: 'OCR',
    confidence: 0.95,
    status: 'COMPLETED',
    errors: [],
    createdAt: '2024-01-15T10:00:00Z',
    updatedAt: '2024-01-15T10:05:00Z',
  },
  {
    id: 'ext_002',
    invoiceId: 'inv_002',
    vendorId: 'vendor_002',
    vendorName: 'Expedia',
    invoiceNumber: 'EXP-2024-002',
    invoiceDate: '2024-01-16T00:00:00Z',
    dueDate: '2024-03-01T00:00:00Z',
    totalAmount: 3500.0,
    currency: 'USD',
    extractedData: {
      headerInfo: {
        invoiceNumber: 'EXP-2024-002',
        vendorAddress: '456 Expedia Way, Seattle',
        customerName: 'Your Hotel Chain',
      },
      lineItems: [
        {
          lineNumber: 1,
          description: 'Hotel Booking - Sheraton Chicago',
          quantity: 1,
          unitPrice: 3500.0,
          amount: 3500.0,
          bookingReference: 'EX789012',
          checkInDate: '2024-02-01T00:00:00Z',
          checkOutDate: '2024-02-05T00:00:00Z',
          guestName: 'Bob Johnson',
          propertyName: 'Sheraton Chicago',
          roomType: 'Presidential Suite',
        },
      ],
      summary: {
        subtotal: 3200.0,
        tax: 280.0,
        fees: 20.0,
        total: 3500.0,
      },
    },
    extractionMethod: 'API',
    confidence: 1.0,
    status: 'COMPLETED',
    errors: [],
    createdAt: '2024-01-16T09:00:00Z',
    updatedAt: '2024-01-16T09:02:00Z',
  },
  {
    id: 'ext_003',
    invoiceId: 'inv_003',
    vendorId: 'vendor_003',
    vendorName: 'Hotels.com',
    invoiceNumber: 'HTC-2024-003',
    invoiceDate: '2024-01-17T00:00:00Z',
    dueDate: '2024-02-16T00:00:00Z',
    totalAmount: 8750.0,
    currency: 'USD',
    extractedData: {
      headerInfo: {
        invoiceNumber: 'HTC-2024-003',
        vendorAddress: '789 Hotels Plaza, Dallas',
        customerName: 'Your Hotel Chain',
        commissionRate: '15%',
      },
      lineItems: [
        {
          lineNumber: 1,
          description: 'Hotel Booking - Four Seasons Miami',
          quantity: 3,
          unitPrice: 450.0,
          amount: 1350.0,
          bookingReference: 'HC456789',
          checkInDate: '2024-02-10T00:00:00Z',
          checkOutDate: '2024-02-13T00:00:00Z',
          guestName: 'Emily Wilson',
          propertyName: 'Four Seasons Miami',
          roomType: 'Ocean View Suite',
        },
        {
          lineNumber: 2,
          description: 'Hotel Booking - Ritz Carlton Orlando',
          quantity: 5,
          unitPrice: 380.0,
          amount: 1900.0,
          bookingReference: 'HC456790',
          checkInDate: '2024-02-15T00:00:00Z',
          checkOutDate: '2024-02-20T00:00:00Z',
          guestName: 'Michael Chen',
          propertyName: 'Ritz Carlton Orlando',
          roomType: 'Club Level Room',
        },
        {
          lineNumber: 3,
          description: 'Hotel Booking - Waldorf Astoria NYC',
          quantity: 2,
          unitPrice: 650.0,
          amount: 1300.0,
          bookingReference: 'HC456791',
          checkInDate: '2024-02-22T00:00:00Z',
          checkOutDate: '2024-02-24T00:00:00Z',
          guestName: 'Sarah Thompson',
          propertyName: 'Waldorf Astoria New York',
          roomType: 'Tower Suite',
        },
      ],
      summary: {
        subtotal: 8000.0,
        tax: 700.0,
        fees: 50.0,
        total: 8750.0,
      },
    },
    extractionMethod: 'EMAIL_PARSER',
    confidence: 0.98,
    status: 'COMPLETED',
    errors: [],
    createdAt: '2024-01-17T11:00:00Z',
    updatedAt: '2024-01-17T11:03:00Z',
  },
  {
    id: 'ext_004',
    invoiceId: 'inv_004',
    vendorId: 'vendor_004',
    vendorName: 'Agoda',
    invoiceNumber: 'AGD-2024-004',
    invoiceDate: '2024-01-18T00:00:00Z',
    dueDate: '2024-03-18T00:00:00Z',
    totalAmount: 6200.0,
    currency: 'EUR',
    extractedData: {
      headerInfo: {
        invoiceNumber: 'AGD-2024-004',
        vendorAddress: '321 Agoda Tower, Singapore',
        customerName: 'Your Hotel Chain Europe',
        propertyId: 'PROP-EU-001',
      },
      lineItems: [
        {
          lineNumber: 1,
          description: 'Hotel Booking - Grand Hotel Paris',
          quantity: 4,
          unitPrice: 420.0,
          amount: 1680.0,
          bookingReference: 'AG987654',
          checkInDate: '2024-03-01T00:00:00Z',
          checkOutDate: '2024-03-05T00:00:00Z',
          guestName: 'Pierre Dubois',
          propertyName: 'Grand Hotel Paris',
          roomType: 'Classic Double',
        },
        {
          lineNumber: 2,
          description: 'Hotel Booking - Hotel Roma Central',
          quantity: 2,
          unitPrice: 350.0,
          amount: 700.0,
          bookingReference: 'AG987655',
          checkInDate: '2024-03-10T00:00:00Z',
          checkOutDate: '2024-03-12T00:00:00Z',
          guestName: 'Maria Rossi',
          propertyName: 'Hotel Roma Central',
          roomType: 'Superior Room',
        },
      ],
      summary: {
        subtotal: 5500.0,
        tax: 660.0,
        fees: 40.0,
        total: 6200.0,
      },
    },
    extractionMethod: 'FTP',
    confidence: 0.99,
    status: 'COMPLETED',
    errors: [],
    createdAt: '2024-01-18T08:30:00Z',
    updatedAt: '2024-01-18T08:35:00Z',
  },
  {
    id: 'ext_005',
    invoiceId: 'inv_005',
    vendorId: 'vendor_001',
    vendorName: 'Booking.com',
    invoiceNumber: 'BKG-2024-005',
    invoiceDate: '2024-01-19T00:00:00Z',
    dueDate: '2024-02-18T00:00:00Z',
    totalAmount: 12500.0,
    currency: 'USD',
    extractedData: {
      headerInfo: {
        invoiceNumber: 'BKG-2024-005',
        vendorAddress: '123 Booking Street, Amsterdam',
        customerName: 'Your Hotel Chain',
      },
      lineItems: [
        {
          lineNumber: 1,
          description: 'Hotel Booking - St. Regis NYC',
          quantity: 5,
          unitPrice: 800.0,
          amount: 4000.0,
          bookingReference: 'BK234567',
          checkInDate: '2024-03-15T00:00:00Z',
          checkOutDate: '2024-03-20T00:00:00Z',
          guestName: 'William Davis',
          propertyName: 'St. Regis New York',
          roomType: 'Madison Suite',
        },
        {
          lineNumber: 2,
          description: 'Hotel Booking - Beverly Hills Hotel',
          quantity: 3,
          unitPrice: 950.0,
          amount: 2850.0,
          bookingReference: 'BK234568',
          checkInDate: '2024-03-22T00:00:00Z',
          checkOutDate: '2024-03-25T00:00:00Z',
          guestName: 'Jennifer Lopez',
          propertyName: 'Beverly Hills Hotel',
          roomType: 'Bungalow Suite',
        },
        {
          lineNumber: 3,
          description: 'Hotel Booking - Plaza Hotel NYC',
          quantity: 2,
          unitPrice: 600.0,
          amount: 1200.0,
          bookingReference: 'BK234569',
          checkInDate: '2024-03-28T00:00:00Z',
          checkOutDate: '2024-03-30T00:00:00Z',
          guestName: 'Robert Brown',
          propertyName: 'The Plaza',
          roomType: 'Fifth Avenue Suite',
        },
      ],
      summary: {
        subtotal: 11250.0,
        tax: 1125.0,
        fees: 125.0,
        total: 12500.0,
      },
    },
    extractionMethod: 'OCR',
    confidence: 0.96,
    status: 'COMPLETED',
    errors: [],
    createdAt: '2024-01-19T14:00:00Z',
    updatedAt: '2024-01-19T14:08:00Z',
  },
  {
    id: 'ext_006',
    invoiceId: 'inv_006',
    vendorId: 'vendor_002',
    vendorName: 'Expedia',
    invoiceNumber: 'EXP-2024-006',
    invoiceDate: '2024-01-20T00:00:00Z',
    dueDate: '2024-03-05T00:00:00Z',
    totalAmount: 4200.0,
    currency: 'USD',
    extractedData: {
      headerInfo: {
        invoiceNumber: 'EXP-2024-006',
        vendorAddress: '456 Expedia Way, Seattle',
        customerName: 'Your Hotel Chain',
      },
      lineItems: [
        {
          lineNumber: 1,
          description: 'Hotel Booking - Hyatt Seattle',
          quantity: 4,
          unitPrice: 280.0,
          amount: 1120.0,
          bookingReference: 'EX890123',
          checkInDate: '2024-04-01T00:00:00Z',
          checkOutDate: '2024-04-05T00:00:00Z',
          guestName: 'David Kim',
          propertyName: 'Hyatt Regency Seattle',
          roomType: 'King Room',
        },
      ],
      summary: {
        subtotal: 3850.0,
        tax: 320.0,
        fees: 30.0,
        total: 4200.0,
      },
    },
    extractionMethod: 'API',
    confidence: 1.0,
    status: 'FAILED',
    errors: [
      {
        code: 'ERR_MISSING_FIELD',
        message: 'Missing guest contact information',
        field: 'guestEmail',
        severity: 'HIGH',
      },
    ],
    createdAt: '2024-01-20T09:00:00Z',
    updatedAt: '2024-01-20T09:05:00Z',
  },
];

export const mockReconciliationSummaries = [
  {
    id: 'recon_001',
    invoiceId: 'inv_001',
    vendorId: 'vendor_001',
    reconciliationDate: '2024-01-16T00:00:00Z',
    totalInvoiceAmount: 5000.0,
    totalReconciledAmount: 4950.0,
    variance: 50.0,
    variancePercentage: 1.0,
    status: 'PARTIAL_MATCH',
    matchedLineItems: 1,
    unmatchedLineItems: 1,
    totalLineItems: 2,
    issues: [
      {
        type: 'AMOUNT_MISMATCH',
        severity: 'LOW',
        description: 'Invoice amount differs from system amount by $50',
        lineItemRef: 'line_002',
        expectedValue: 900.0,
        actualValue: 850.0,
        variance: 50.0,
      },
    ],
    approvalStatus: 'PENDING',
    approvedBy: null,
    approvalDate: null,
    notes: 'Minor variance within acceptable threshold',
    createdAt: '2024-01-16T10:00:00Z',
    updatedAt: '2024-01-16T10:00:00Z',
  },
  {
    id: 'recon_002',
    invoiceId: 'inv_002',
    vendorId: 'vendor_002',
    reconciliationDate: '2024-01-17T00:00:00Z',
    totalInvoiceAmount: 3500.0,
    totalReconciledAmount: 3500.0,
    variance: 0.0,
    variancePercentage: 0.0,
    status: 'MATCHED',
    matchedLineItems: 1,
    unmatchedLineItems: 0,
    totalLineItems: 1,
    issues: [],
    approvalStatus: 'APPROVED',
    approvedBy: 'system',
    approvalDate: '2024-01-17T10:00:00Z',
    notes: 'Auto-approved - perfect match',
    createdAt: '2024-01-17T10:00:00Z',
    updatedAt: '2024-01-17T10:00:00Z',
  },
  {
    id: 'recon_003',
    invoiceId: 'inv_003',
    vendorId: 'vendor_003',
    reconciliationDate: '2024-01-18T00:00:00Z',
    totalInvoiceAmount: 8750.0,
    totalReconciledAmount: 8600.0,
    variance: 150.0,
    variancePercentage: 1.71,
    status: 'PARTIAL_MATCH',
    matchedLineItems: 2,
    unmatchedLineItems: 1,
    totalLineItems: 3,
    issues: [
      {
        type: 'BOOKING_NOT_FOUND',
        severity: 'HIGH',
        description: 'Booking reference not found in system',
        lineItemRef: 'line_003',
        expectedValue: 'HC456791',
        actualValue: null,
        variance: 1300.0,
      },
      {
        type: 'TAX_MISMATCH',
        severity: 'MEDIUM',
        description: 'Tax calculation differs from invoice',
        lineItemRef: 'summary',
        expectedValue: 750.0,
        actualValue: 700.0,
        variance: 50.0,
      },
    ],
    approvalStatus: 'REVIEW_REQUIRED',
    approvedBy: null,
    approvalDate: null,
    notes: 'Manual review needed - booking not found',
    createdAt: '2024-01-18T12:00:00Z',
    updatedAt: '2024-01-18T12:00:00Z',
  },
  {
    id: 'recon_004',
    invoiceId: 'inv_004',
    vendorId: 'vendor_004',
    reconciliationDate: '2024-01-19T00:00:00Z',
    totalInvoiceAmount: 6200.0,
    totalReconciledAmount: 6200.0,
    variance: 0.0,
    variancePercentage: 0.0,
    status: 'MATCHED',
    matchedLineItems: 2,
    unmatchedLineItems: 0,
    totalLineItems: 2,
    issues: [],
    approvalStatus: 'APPROVED',
    approvedBy: 'system',
    approvalDate: '2024-01-19T09:00:00Z',
    notes: 'Auto-approved - perfect match',
    createdAt: '2024-01-19T09:00:00Z',
    updatedAt: '2024-01-19T09:00:00Z',
  },
  {
    id: 'recon_005',
    invoiceId: 'inv_005',
    vendorId: 'vendor_001',
    reconciliationDate: '2024-01-20T00:00:00Z',
    totalInvoiceAmount: 12500.0,
    totalReconciledAmount: 12450.0,
    variance: 50.0,
    variancePercentage: 0.4,
    status: 'MATCHED',
    matchedLineItems: 3,
    unmatchedLineItems: 0,
    totalLineItems: 3,
    issues: [
      {
        type: 'AMOUNT_MISMATCH',
        severity: 'LOW',
        description: 'Minor rounding difference in tax calculation',
        lineItemRef: 'summary',
        expectedValue: 1175.0,
        actualValue: 1125.0,
        variance: 50.0,
      },
    ],
    approvalStatus: 'APPROVED',
    approvedBy: 'system',
    approvalDate: '2024-01-20T15:00:00Z',
    notes: 'Auto-approved - variance within tolerance',
    createdAt: '2024-01-20T15:00:00Z',
    updatedAt: '2024-01-20T15:00:00Z',
  },
  {
    id: 'recon_006',
    invoiceId: 'inv_006',
    vendorId: 'vendor_002',
    reconciliationDate: '2024-01-21T00:00:00Z',
    totalInvoiceAmount: 4200.0,
    totalReconciledAmount: 0.0,
    variance: 4200.0,
    variancePercentage: 100.0,
    status: 'FAILED',
    matchedLineItems: 0,
    unmatchedLineItems: 1,
    totalLineItems: 1,
    issues: [
      {
        type: 'EXTRACTION_FAILED',
        severity: 'CRITICAL',
        description: 'Failed to extract invoice data',
        lineItemRef: null,
        expectedValue: null,
        actualValue: null,
        variance: 4200.0,
      },
    ],
    approvalStatus: 'REJECTED',
    approvedBy: 'admin',
    approvalDate: '2024-01-21T10:00:00Z',
    notes: 'Extraction failed - manual processing required',
    createdAt: '2024-01-21T10:00:00Z',
    updatedAt: '2024-01-21T10:00:00Z',
  },
];

export const mockRules = [
  {
    id: 'rule_001',
    vendorId: 'vendor_001',
    ruleName: 'Amount Tolerance Check',
    description: 'Check if invoice amount is within 1% tolerance',
    ruleType: 'VALIDATION',
    category: 'FINANCIAL',
    isActive: true,
    priority: 1,
    conditions: [
      {
        field: 'amount_variance_percentage',
        operator: 'LESS_THAN',
        value: 1,
        dataType: 'NUMBER',
      },
    ],
    actions: [
      {
        type: 'AUTO_APPROVE',
        parameters: {
          reason: 'Within tolerance',
        },
      },
    ],
    tolerance: {
      type: 'PERCENTAGE',
      value: 1,
    },
    effectiveFrom: '2024-01-01T00:00:00Z',
    effectiveTo: null,
    createdBy: 'admin',
    createdAt: '2024-01-01T00:00:00Z',
    updatedAt: '2024-01-01T00:00:00Z',
    lastUsed: '2024-01-20T15:00:00Z',
    usageCount: 250,
  },
  {
    id: 'rule_002',
    vendorId: 'vendor_001',
    ruleName: 'Booking Reference Match',
    description: 'Ensure booking reference exists in our system',
    ruleType: 'MATCHING',
    category: 'BOOKING',
    isActive: true,
    priority: 2,
    conditions: [
      {
        field: 'booking_reference',
        operator: 'NOT_EQUALS',
        value: null,
        dataType: 'STRING',
      },
    ],
    actions: [
      {
        type: 'FLAG',
        parameters: {
          flag: 'BOOKING_VERIFIED',
        },
      },
    ],
    tolerance: null,
    effectiveFrom: '2024-01-01T00:00:00Z',
    effectiveTo: null,
    createdBy: 'admin',
    createdAt: '2024-01-01T00:00:00Z',
    updatedAt: '2024-01-01T00:00:00Z',
    lastUsed: '2024-01-20T15:00:00Z',
    usageCount: 320,
  },
  {
    id: 'rule_003',
    vendorId: 'vendor_002',
    ruleName: 'Expedia Date Validation',
    description: 'Validate check-in dates are in the future',
    ruleType: 'VALIDATION',
    category: 'BOOKING',
    isActive: true,
    priority: 1,
    conditions: [
      {
        field: 'check_in_date',
        operator: 'GREATER_THAN',
        value: 'TODAY',
        dataType: 'DATE',
      },
    ],
    actions: [
      {
        type: 'CONTINUE',
        parameters: {},
      },
    ],
    tolerance: null,
    effectiveFrom: '2024-01-01T00:00:00Z',
    effectiveTo: null,
    createdBy: 'admin',
    createdAt: '2024-01-01T00:00:00Z',
    updatedAt: '2024-01-01T00:00:00Z',
    lastUsed: '2024-01-21T10:00:00Z',
    usageCount: 180,
  },
  {
    id: 'rule_004',
    vendorId: 'vendor_002',
    ruleName: 'Expedia Tax Validation',
    description: 'Validate tax calculations for Expedia invoices',
    ruleType: 'VALIDATION',
    category: 'FINANCIAL',
    isActive: true,
    priority: 3,
    conditions: [
      {
        field: 'tax_rate',
        operator: 'BETWEEN',
        value: { min: 5, max: 15 },
        dataType: 'NUMBER',
      },
    ],
    actions: [
      {
        type: 'VALIDATE_TAX',
        parameters: {
          method: 'RECALCULATE',
        },
      },
    ],
    tolerance: {
      type: 'ABSOLUTE',
      value: 10,
    },
    effectiveFrom: '2024-01-01T00:00:00Z',
    effectiveTo: null,
    createdBy: 'admin',
    createdAt: '2024-01-01T00:00:00Z',
    updatedAt: '2024-01-01T00:00:00Z',
    lastUsed: '2024-01-21T10:00:00Z',
    usageCount: 150,
  },
  {
    id: 'rule_005',
    vendorId: 'vendor_003',
    ruleName: 'Hotels.com Commission Rate',
    description: 'Validate commission rate is within agreed range',
    ruleType: 'VALIDATION',
    category: 'FINANCIAL',
    isActive: true,
    priority: 1,
    conditions: [
      {
        field: 'commission_rate',
        operator: 'BETWEEN',
        value: { min: 10, max: 20 },
        dataType: 'NUMBER',
      },
    ],
    actions: [
      {
        type: 'FLAG',
        parameters: {
          flag: 'COMMISSION_VALID',
        },
      },
    ],
    tolerance: null,
    effectiveFrom: '2024-01-01T00:00:00Z',
    effectiveTo: null,
    createdBy: 'admin',
    createdAt: '2024-01-01T00:00:00Z',
    updatedAt: '2024-01-01T00:00:00Z',
    lastUsed: '2024-01-18T12:00:00Z',
    usageCount: 75,
  },
  {
    id: 'rule_006',
    vendorId: 'vendor_004',
    ruleName: 'Agoda Property Validation',
    description: 'Validate property ID matches our records',
    ruleType: 'MATCHING',
    category: 'PROPERTY',
    isActive: true,
    priority: 1,
    conditions: [
      {
        field: 'property_id',
        operator: 'EXISTS_IN',
        value: 'PROPERTY_MASTER',
        dataType: 'STRING',
      },
    ],
    actions: [
      {
        type: 'FLAG',
        parameters: {
          flag: 'PROPERTY_VERIFIED',
        },
      },
    ],
    tolerance: null,
    effectiveFrom: '2024-01-01T00:00:00Z',
    effectiveTo: null,
    createdBy: 'admin',
    createdAt: '2024-01-01T00:00:00Z',
    updatedAt: '2024-01-01T00:00:00Z',
    lastUsed: '2024-01-19T09:00:00Z',
    usageCount: 45,
  },
  {
    id: 'rule_007',
    vendorId: 'vendor_004',
    ruleName: 'Agoda Currency Conversion',
    description: 'Apply currency conversion for EUR invoices',
    ruleType: 'TRANSFORMATION',
    category: 'FINANCIAL',
    isActive: true,
    priority: 2,
    conditions: [
      {
        field: 'currency',
        operator: 'EQUALS',
        value: 'EUR',
        dataType: 'STRING',
      },
    ],
    actions: [
      {
        type: 'CONVERT_CURRENCY',
        parameters: {
          targetCurrency: 'USD',
          rateSource: 'DAILY_RATES',
        },
      },
    ],
    tolerance: null,
    effectiveFrom: '2024-01-01T00:00:00Z',
    effectiveTo: null,
    createdBy: 'admin',
    createdAt: '2024-01-01T00:00:00Z',
    updatedAt: '2024-01-01T00:00:00Z',
    lastUsed: '2024-01-19T09:00:00Z',
    usageCount: 30,
  },
  {
    id: 'rule_008',
    vendorId: 'vendor_005',
    ruleName: 'TripAdvisor Referral Validation',
    description: 'Validate referral tracking codes',
    ruleType: 'VALIDATION',
    category: 'BOOKING',
    isActive: false,
    priority: 1,
    conditions: [
      {
        field: 'referral_code',
        operator: 'MATCHES_PATTERN',
        value: '^TA[0-9]{8}$',
        dataType: 'STRING',
      },
    ],
    actions: [
      {
        type: 'FLAG',
        parameters: {
          flag: 'REFERRAL_VALID',
        },
      },
    ],
    tolerance: null,
    effectiveFrom: '2023-11-01T00:00:00Z',
    effectiveTo: '2024-01-10T00:00:00Z',
    createdBy: 'admin',
    createdAt: '2023-11-01T00:00:00Z',
    updatedAt: '2024-01-10T00:00:00Z',
    lastUsed: '2024-01-10T00:00:00Z',
    usageCount: 120,
  },
  {
    id: 'rule_009',
    vendorId: null,
    ruleName: 'Global Duplicate Check',
    description: 'Check for duplicate invoices across all vendors',
    ruleType: 'VALIDATION',
    category: 'DUPLICATE',
    isActive: true,
    priority: 1,
    conditions: [
      {
        field: 'invoice_hash',
        operator: 'NOT_EXISTS_IN',
        value: 'PROCESSED_INVOICES',
        dataType: 'STRING',
      },
    ],
    actions: [
      {
        type: 'FLAG',
        parameters: {
          flag: 'NO_DUPLICATE',
        },
      },
    ],
    tolerance: null,
    effectiveFrom: '2024-01-01T00:00:00Z',
    effectiveTo: null,
    createdBy: 'system',
    createdAt: '2024-01-01T00:00:00Z',
    updatedAt: '2024-01-01T00:00:00Z',
    lastUsed: '2024-01-21T10:00:00Z',
    usageCount: 450,
  },
  {
    id: 'rule_010',
    vendorId: null,
    ruleName: 'Large Amount Alert',
    description: 'Flag invoices over $10,000 for manual review',
    ruleType: 'ALERT',
    category: 'FINANCIAL',
    isActive: true,
    priority: 2,
    conditions: [
      {
        field: 'total_amount',
        operator: 'GREATER_THAN',
        value: 10000,
        dataType: 'NUMBER',
      },
    ],
    actions: [
      {
        type: 'REQUIRE_APPROVAL',
        parameters: {
          approvalLevel: 'MANAGER',
          notification: true,
        },
      },
    ],
    tolerance: null,
    effectiveFrom: '2024-01-01T00:00:00Z',
    effectiveTo: null,
    createdBy: 'finance_manager',
    createdAt: '2024-01-01T00:00:00Z',
    updatedAt: '2024-01-01T00:00:00Z',
    lastUsed: '2024-01-20T15:00:00Z',
    usageCount: 25,
  },
];

export const mockReconciliationStatus = {
  id: 'status_001',
  invoiceId: 'inv_001',
  vendorId: 'vendor_001',
  currentStage: 'RECONCILING',
  overallStatus: 'IN_PROGRESS',
  startedAt: '2024-01-16T10:00:00Z',
  completedAt: null,
  progress: {
    extraction: {
      status: 'COMPLETED',
      percentage: 100,
      startTime: '2024-01-16T10:00:00Z',
      endTime: '2024-01-16T10:05:00Z',
      message: 'Extraction completed successfully',
    },
    validation: {
      status: 'COMPLETED',
      percentage: 100,
      startTime: '2024-01-16T10:05:00Z',
      endTime: '2024-01-16T10:10:00Z',
      message: 'Validation passed',
    },
    reconciliation: {
      status: 'IN_PROGRESS',
      percentage: 60,
      startTime: '2024-01-16T10:10:00Z',
      endTime: null,
      message: 'Matching line items...',
    },
  },
  errors: [],
  warnings: [
    {
      code: 'W001',
      message: 'Minor amount variance detected',
      timestamp: '2024-01-16T10:12:00Z',
      details: {
        variance: 50.0,
      },
    },
  ],
  metadata: {
    processedBy: 'system',
    rulesApplied: ['rule_001', 'rule_002'],
  },
  lastUpdated: '2024-01-16T10:12:00Z',
};

export const mockStatistics = {
  activeVendors: 15,
  totalExtractions: 1250,
  totalReconciliations: 1200,
  totalInvoiceAmount: 2500000.0,
  totalReconciledAmount: 2450000.0,
  averageVariance: 0.5,
  pendingInvoices: 50,
  disputedInvoices: 10,
  successRate: 96.5,
  monthlyTrend: [
    {
      month: '2024-01',
      invoices: 150,
      amount: 300000,
      reconciled: 145,
    },
    {
      month: '2023-12',
      invoices: 180,
      amount: 350000,
      reconciled: 175,
    },
    {
      month: '2023-11',
      invoices: 160,
      amount: 320000,
      reconciled: 155,
    },
    {
      month: '2023-10',
      invoices: 140,
      amount: 280000,
      reconciled: 138,
    },
    {
      month: '2023-09',
      invoices: 130,
      amount: 260000,
      reconciled: 128,
    },
    {
      month: '2023-08',
      invoices: 170,
      amount: 340000,
      reconciled: 165,
    },
  ],
  vendorPerformance: [
    {
      vendorId: 'vendor_001',
      vendorName: 'Booking.com',
      totalInvoices: 450,
      successRate: 98.2,
      averageProcessingTime: 5.2,
      totalAmount: 850000,
    },
    {
      vendorId: 'vendor_002',
      vendorName: 'Expedia',
      totalInvoices: 380,
      successRate: 95.5,
      averageProcessingTime: 6.8,
      totalAmount: 720000,
    },
    {
      vendorId: 'vendor_003',
      vendorName: 'Hotels.com',
      totalInvoices: 320,
      successRate: 97.1,
      averageProcessingTime: 4.5,
      totalAmount: 620000,
    },
    {
      vendorId: 'vendor_004',
      vendorName: 'Agoda',
      totalInvoices: 250,
      successRate: 96.8,
      averageProcessingTime: 5.0,
      totalAmount: 480000,
    },
  ],
  issuesByType: [
    {
      type: 'AMOUNT_MISMATCH',
      count: 45,
      percentage: 35,
    },
    {
      type: 'BOOKING_NOT_FOUND',
      count: 25,
      percentage: 20,
    },
    {
      type: 'TAX_MISMATCH',
      count: 20,
      percentage: 15,
    },
    {
      type: 'DUPLICATE_INVOICE',
      count: 15,
      percentage: 12,
    },
    {
      type: 'DATE_MISMATCH',
      count: 10,
      percentage: 8,
    },
    {
      type: 'OTHER',
      count: 13,
      percentage: 10,
    },
  ],
  processingTimeDistribution: {
    under5Min: 750,
    between5And10Min: 350,
    between10And30Min: 120,
    over30Min: 30,
  },
};

export const mockInvoiceHistory = [
  {
    id: 'hist_001',
    invoiceId: 'inv_001',
    action: 'CREATED',
    timestamp: '2024-01-15T10:00:00Z',
    performedBy: 'system',
    details: {
      source: 'EMAIL',
      fileName: 'booking_invoice_jan.pdf',
    },
  },
  {
    id: 'hist_002',
    invoiceId: 'inv_001',
    action: 'EXTRACTION_STARTED',
    timestamp: '2024-01-15T10:01:00Z',
    performedBy: 'system',
    details: {
      method: 'OCR',
    },
  },
  {
    id: 'hist_003',
    invoiceId: 'inv_001',
    action: 'EXTRACTION_COMPLETED',
    timestamp: '2024-01-15T10:05:00Z',
    performedBy: 'system',
    details: {
      confidence: 0.95,
      itemsExtracted: 2,
    },
  },
  {
    id: 'hist_004',
    invoiceId: 'inv_001',
    action: 'RECONCILIATION_STARTED',
    timestamp: '2024-01-16T10:00:00Z',
    performedBy: 'system',
    details: {
      rulesApplied: ['rule_001', 'rule_002'],
    },
  },
  {
    id: 'hist_005',
    invoiceId: 'inv_001',
    action: 'ISSUE_DETECTED',
    timestamp: '2024-01-16T10:12:00Z',
    performedBy: 'system',
    details: {
      issueType: 'AMOUNT_MISMATCH',
      variance: 50.0,
    },
  },
];

export const mockNotifications = [
  {
    id: 'notif_001',
    type: 'APPROVAL_REQUIRED',
    priority: 'HIGH',
    title: 'Large Invoice Approval Required',
    message: 'Invoice BKG-2024-005 for $12,500 requires manager approval',
    relatedEntity: {
      type: 'INVOICE',
      id: 'inv_005',
    },
    createdAt: '2024-01-20T15:00:00Z',
    readAt: null,
    actionRequired: true,
  },
  {
    id: 'notif_002',
    type: 'RECONCILIATION_FAILED',
    priority: 'MEDIUM',
    title: 'Reconciliation Failed',
    message: 'Failed to reconcile invoice EXP-2024-006 due to extraction errors',
    relatedEntity: {
      type: 'INVOICE',
      id: 'inv_006',
    },
    createdAt: '2024-01-21T10:00:00Z',
    readAt: null,
    actionRequired: true,
  },
  {
    id: 'notif_003',
    type: 'VENDOR_UPDATE',
    priority: 'LOW',
    title: 'Vendor Settings Updated',
    message: 'Hotels.com invoice settings have been updated',
    relatedEntity: {
      type: 'VENDOR',
      id: 'vendor_003',
    },
    createdAt: '2024-01-25T14:20:00Z',
    readAt: '2024-01-25T15:00:00Z',
    actionRequired: false,
  },
];

export const mockDashboardMetrics = {
  todayMetrics: {
    invoicesReceived: 12,
    invoicesProcessed: 10,
    invoicesReconciled: 8,
    totalAmount: 45000,
    issuesDetected: 2,
  },
  weekMetrics: {
    invoicesReceived: 65,
    invoicesProcessed: 58,
    invoicesReconciled: 52,
    totalAmount: 280000,
    issuesDetected: 8,
  },
  processingQueue: {
    awaitingExtraction: 5,
    awaitingValidation: 3,
    awaitingReconciliation: 7,
    awaitingApproval: 4,
  },
  topIssues: [
    {
      vendorName: 'Booking.com',
      issueCount: 3,
      primaryIssue: 'Amount mismatches',
    },
    {
      vendorName: 'Expedia',
      issueCount: 2,
      primaryIssue: 'Missing bookings',
    },
    {
      vendorName: 'Hotels.com',
      issueCount: 1,
      primaryIssue: 'Tax calculation errors',
    },
  ],
  recentActivity: [
    {
      timestamp: '2024-01-21T15:30:00Z',
      action: 'Invoice approved',
      invoice: 'BKG-2024-005',
      user: 'admin',
    },
    {
      timestamp: '2024-01-21T15:15:00Z',
      action: 'Reconciliation completed',
      invoice: 'AGD-2024-004',
      user: 'system',
    },
    {
      timestamp: '2024-01-21T14:45:00Z',
      action: 'Issue resolved',
      invoice: 'HTC-2024-003',
      user: 'finance_user',
    },
  ],
};
